---
# This playbook deploys a simple standalone Tomcat 7 server.
- name: Prepare host

  hosts: localhost
  connection: local

  gather_facts: yes

#  vars_files:

#  vars:

#  roles:

  tasks:
    - debug:
        msg: ansible_facts

    - import_tasks: ubuntu.yml
      when: ansible_facts['os_family'] in ['Debian','Ubuntu']

    - import_tasks: centos.yml
      when: ansible_facts['os_family'] in ['CentOS','RedHat']

    - block:

      - name: flush handlers
        meta: flush_handlers

  become: True
