---
# This playbook deploys a simple standalone Tomcat 7 server.
- name: Prepare host

  hosts: localhost
  connection: local

  gather_facts: yes

  # vars_files:
  #   - vars/main.yml

#  vars:

  roles:
    - linux-configuration

#  tasks:
