---
  - name: install software with yum
    raw: "yum -y install {{ bootstrap_yum_packages }}"
    register: yumresult
    changed_when:
      - "'Nothing' not in yumresult.stdout"
    until: yumresult is succeeded
    retries: 3
