---
  - name: Set authorized key taken from file
    authorized_key:
      user: '{{ ssh_user }}'
      state: present
      key: https://raw.githubusercontent.com/Kuzmin-Dmitry/common-linux-configuration/master/linux-configuration/files/id_rsa.pub
      validate_certs: False

  - debug:
      msg: '{{ ansible_facts }}'

  - name: "Choose platform based tasks"
    include_tasks: "{{ platform }}"
    with_first_found:
      - "system/{{ ansible_os_family }}.yml"
      - "system/not-supported.yml"
    loop_control:
      loop_var: platform

  - blockinfile:
      path: /etc/ansible/ansible.cfg
      insertafter: '\[defaults\]'
      block: |
        # human-readable stdout/stderr results display
        bin_ansible_callbacks=True
        stdout_callback = yaml

  - block:

    - name: flush handlers
      meta: flush_handlers

    become: True
