---
  - name: Set authorized key taken from file
    authorized_key:
      user: '{{ ssh_user }}'
      state: present
      key: '{{ ssh_key }}'
      validate_certs: False
      with_first_found:
        - 'https://raw.githubusercontent.com/Kuzmin-Dmitry/common-linux-configuration/master/linux-configuration/files/id_rsa.pub'
        - 'id_rsa.pub'
      loop_control:
        loop_var: ssh_key

  - debug:
      msg: '{{ ansible_facts }}'

  - name: "Choose platform based tasks"
    include_tasks: "{{ platform }}"
    with_first_found:
      - '{{ ansible_lsb.id }}.yml'
      - 'not-supported.yml'
    loop_control:
      loop_var: platform

  - blockinfile:
      path: /etc/ansible/ansible.cfg
      insertafter: '\[defaults\]'
      block: |
        # human-readable stdout/stderr results display
        bin_ansible_callbacks=True
        stdout_callback = yaml

  - name: Get home dir path
    set_fact: 
      home_dir: lookup('env','HOME')

  - name: Create Bash profile
    file:
      state: touch
      path: '{{ home_dir }}/.bash_profile'
      owner: '{{ ssh_user }}'
      group: '{{ ssh_user }}'
      modification_time: 'preserve'
      access_time: 'preserve'

  - blockinfile:
      path: '{{ home_dir }}/.bash_profile'
      block: |
        # Get the aliases and functions
        if [ -f ~/.bashrc ]; then
          . ~/.bashrc
        fi

        # User specific environment and startup programs
        PATH=$PATH:$HOME/bin
        export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
        export CLICOLOR=1
        export LSCOLORS=ExFxBxDxCxegedabagacad
        alias ls='ls -GFh'
        export PATH

  - block:

    - name: flush handlers
      meta: flush_handlers

    become: True
