---
  - name: install software with apt-get
    raw: "apt-get update ; apt-get -y install {{ bootstrap_apt_packages }}"
    register: apt_getresult
    changed_when:
      - "' 0 newly installed' not in apt_getresult.stdout"
    until: apt_getresult is succeeded
    retries: 3
